### ISSUE TITLE
Running VeriNet on cluster

### ISSUE THREAD

**Issue by AWbosman** [vas-group-imperial/VeriNet#5]
Currently I am trying to run VeriNet on my cluster. With this simple code block following the read.me tutorial:

```from verinet.parsers.onnx_parser import ONNXParser
from verinet.parsers.vnnlib_parser import VNNLIBParser
from verinet.verification.verinet import VeriNet


#we can load our onnx networks
onnx_parser = ONNXParser(model_path)
model = onnx_parser.to_pytorch()
model.eval()

#now we need to import vnnlib
vnnlib_parser = VNNLIBParser(vnnlib_path)
objectives = vnnlib_parser.get_objectives_from_vnnlib(model, (784,))
```

 However, this error occurs:

``` Traceback (most recent call last):
  File "/software/python3.7.15/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/python3.7.15/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python3.7.15/lib/python3.7/multiprocessing/managers.py", line 597, in _run_server
    server.serve_forever()
  File "/software/python3.7.15/lib/python3.7/multiprocessing/managers.py", line 173, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/python3.7.15/lib/python3.7/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/software/python3.7.15/lib/python3.7/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/software/python3.7.15/lib/python3.7/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/software/python3.7.15/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/software/python3.7.15/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/software/python3.7.15/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000005bce20000055be'
```

I was wondering if anyone has ever seen this issue and knows how to handle it.

**Comment by pat676** [comment]
Hi, we have not encountered this error before. 

This seems to be an OS/ Multiprocessing related error; which OS are your running? VeriNet has only been used extensively with Ubuntu and Fedora, it most likely will not run on macOS and definitively not on Windows. 

A google search also suggested that this may be related to running out of space in virtual machines (https://github.com/fenderglass/Flye/issues/328). Are you running VeriNet in a virtual machine?

**Comment by AWbosman** [comment]
Hi, Thanks for the quick reply! 
The OS is CentOS 7 and I am running VeriNet within a  python virtual environment. I will take a look at the issue you send me as well. 
It also starts occuring when calling the vnnlib parser, is that class using the multiprocessing?

**Comment by pat676** [comment]
Assuming this Issue was resolved, please reopen if not correct.
